sudo: required
language: csharp
solution: src/dockerTest.sln
services:
  - docker
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-1-003177
      mono: none
      env: DOTNETCORE=1
script:

  - chmod +x ./scripts/build.sh

  - ./scripts/build.sh
