sudo: required
language: csharp
solution: src/dockerTest.sln
services:
- docker
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    dotnet: 1.0.0-preview2-1-003177
    mono: none
    env: DOTNETCORE=1
script:
- chmod +x ./scripts/build.sh
- cd scripts
- "./build.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_1e09b1a8aab1_key -iv $encrypted_1e09b1a8aab1_iv
  -in ssh_host_rsa_key.enc -out ssh_host_rsa_key -d
after_success:
- scp blah root@138.197.211.203/home/dona/ 
